spring.application.name=AplikacjaFitnesSilownia
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=KhadaJhin420$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
